#!/usr/bin/python2
import json
import sys


with open(sys.argv[1]) as f:
    a = [x[2:].strip() for x in f.readlines()]
    if sys.argv[2] == 'ALL':
	print(', '.join(a))
    elif sys.argv[2].isdigit:
	print(a[int(sys.argv[2]) - 1])
